name: Testnet Deploy

on:
  push:
    branches: [ "testnet" ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ⚙️
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Lint code
      run: |
        yarn lint-tests-check
        yarn lint-contracts-check

    - name: Test truffle
      run: yarn test

  deploy:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ⚙️
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Deploy
      run: |
        yarn truffle deploy --network ropsten

    - name: Verify Contract
      run: |
        yarn truffle run verify Vinci --network ropsten
